services:
  customers-api:
    build:
      context: .
      dockerfile: Services/G2CarRentalCustomers/Dockerfile
    container_name: customers-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Data Source=customers.db"
    ports:
      - "7058:8080"

  maintenance-api:
    build:
      context: .
      dockerfile: Services/G2Maintenance/G2Maintenance.WebAPI/Dockerfile
    container_name: maintenance-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Data Source=maintenance.db"
    ports:
      - "7123:8080"

  vehicleinventory-api:
    build:
      context: .
      dockerfile: Services/G2VehicleInventory/G2VehicleInventory.WebAPI/Dockerfile
    container_name: vehicleinventory-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Data Source=vehicleinventory.db"
    ports:
      - "7182:8080"

  api-gateway:
    build:
      context: .
      dockerfile: G2API_Gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - customers-api
      - maintenance-api
      - vehicleinventory-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ReverseProxy__Clusters__maintenance-cluster__Destinations__destination1__Address: "http://maintenance-api:8080"
      ReverseProxy__Clusters__car-rental-customer-cluster__Destinations__destination1__Address: "http://customers-api:8080"
      ReverseProxy__Clusters__vehicleinventory-cluster__Destinations__destination1__Address: "http://vehicleinventory-api:8080"
    ports:
      - "7298:8080"

  carrental-mvc:
    build:
      context: .
      dockerfile: Applications/CarRentalPlatform/Dockerfile
    container_name: carrental-mvc
    depends_on:
      - api-gateway
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ApiGateway__BaseUrl: "http://api-gateway:8080/"
      ConnectionStrings__DefaultConnection: "Data Source=customers.db"
    ports:
      - "7045:8080"