apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-api
  template:
    metadata:
      labels:
        app: customers-api
    spec:
      containers:
        - name: customers-api
          image: customers-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver,1433;Database=CustomerProfile;User Id=sa;Password=Password111!;TrustServerCertificate=True;Encrypt=False"
